// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentStatus.
const (
	AgentStatusActive   AgentStatus = "active"
	AgentStatusInactive AgentStatus = "inactive"
)

// Defines values for CreateTaskRequestType.
const (
	CreateTaskRequestTypeExec CreateTaskRequestType = "exec"
)

// Defines values for CreateTemplateTaskRequestType.
const (
	CreateTemplateTaskRequestTypeExec CreateTemplateTaskRequestType = "exec"
)

// Defines values for DebugTaskStatus.
const (
	DebugTaskStatusFailed  DebugTaskStatus = "failed"
	DebugTaskStatusPending DebugTaskStatus = "pending"
	DebugTaskStatusRunning DebugTaskStatus = "running"
	DebugTaskStatusSkipped DebugTaskStatus = "skipped"
	DebugTaskStatusSuccess DebugTaskStatus = "success"
)

// Defines values for TaskType.
const (
	TaskTypeExec TaskType = "exec"
)

// Defines values for TaskExecutionStatus.
const (
	TaskExecutionStatusFailed  TaskExecutionStatus = "failed"
	TaskExecutionStatusPending TaskExecutionStatus = "pending"
	TaskExecutionStatusRunning TaskExecutionStatus = "running"
	TaskExecutionStatusSkipped TaskExecutionStatus = "skipped"
	TaskExecutionStatusSuccess TaskExecutionStatus = "success"
)

// Defines values for TemplateTaskType.
const (
	TemplateTaskTypeExec TemplateTaskType = "exec"
)

// Defines values for ListExecutionsParamsStatus.
const (
	ListExecutionsParamsStatusFailed  ListExecutionsParamsStatus = "failed"
	ListExecutionsParamsStatusPending ListExecutionsParamsStatus = "pending"
	ListExecutionsParamsStatusRunning ListExecutionsParamsStatus = "running"
	ListExecutionsParamsStatusSkipped ListExecutionsParamsStatus = "skipped"
	ListExecutionsParamsStatusSuccess ListExecutionsParamsStatus = "success"
)

// Agent defines model for Agent.
type Agent struct {
	ClusterId     openapi_types.UUID `json:"cluster_id"`
	Hostname      string             `json:"hostname"`
	Id            openapi_types.UUID `json:"id"`
	LastHeartbeat time.Time          `json:"last_heartbeat"`
	RegisteredAt  time.Time          `json:"registered_at"`
	Status        AgentStatus        `json:"status"`
}

// AgentStatus defines model for Agent.Status.
type AgentStatus string

// Cluster defines model for Cluster.
type Cluster struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// CreateClusterRequest defines model for CreateClusterRequest.
type CreateClusterRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateDebugTaskRequest defines model for CreateDebugTaskRequest.
type CreateDebugTaskRequest struct {
	AgentId openapi_types.UUID `json:"agent_id"`
	Command string             `json:"command"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Blocking  *bool                 `json:"blocking,omitempty"`
	ClusterId openapi_types.UUID    `json:"cluster_id"`
	Config    TaskConfig            `json:"config"`
	Name      string                `json:"name"`
	Type      CreateTaskRequestType `json:"type"`
}

// CreateTaskRequestType defines model for CreateTaskRequest.Type.
type CreateTaskRequestType string

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateTemplateTaskRequest defines model for CreateTemplateTaskRequest.
type CreateTemplateTaskRequest struct {
	Blocking *bool                         `json:"blocking,omitempty"`
	Config   TaskConfig                    `json:"config"`
	Name     string                        `json:"name"`
	Type     CreateTemplateTaskRequestType `json:"type"`
}

// CreateTemplateTaskRequestType defines model for CreateTemplateTaskRequest.Type.
type CreateTemplateTaskRequestType string

// DebugTask defines model for DebugTask.
type DebugTask struct {
	AgentId     openapi_types.UUID `json:"agent_id"`
	Command     string             `json:"command"`
	CompletedAt *time.Time         `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	Error       *string            `json:"error,omitempty"`
	ExitCode    *int               `json:"exit_code"`
	Id          openapi_types.UUID `json:"id"`
	Output      *string            `json:"output,omitempty"`
	Status      DebugTaskStatus    `json:"status"`
}

// DebugTaskStatus defines model for DebugTask.Status.
type DebugTaskStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// ExportTemplateRequest defines model for ExportTemplateRequest.
type ExportTemplateRequest struct {
	// TaskIds Optional array of task IDs to export. If empty or omitted, all tasks are exported.
	TaskIds             *[]openapi_types.UUID `json:"task_ids,omitempty"`
	TemplateDescription *string               `json:"template_description,omitempty"`
	TemplateName        string                `json:"template_name"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status *string `json:"status,omitempty"`
}

// ImportTemplateRequest defines model for ImportTemplateRequest.
type ImportTemplateRequest struct {
	TemplateId openapi_types.UUID `json:"template_id"`
}

// ImportTemplateResponse defines model for ImportTemplateResponse.
type ImportTemplateResponse struct {
	Message       string `json:"message"`
	TasksImported int    `json:"tasks_imported"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
	Total  int `json:"total"`
}

// ReorderTasksRequest defines model for ReorderTasksRequest.
type ReorderTasksRequest struct {
	ClusterId openapi_types.UUID   `json:"cluster_id"`
	TaskIds   []openapi_types.UUID `json:"task_ids"`
}

// Task defines model for Task.
type Task struct {
	Blocking  bool               `json:"blocking"`
	ClusterId openapi_types.UUID `json:"cluster_id"`
	Config    TaskConfig         `json:"config"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt *time.Time         `json:"deleted_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Order     int                `json:"order"`
	Type      TaskType           `json:"type"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// TaskType defines model for Task.Type.
type TaskType string

// TaskConfig defines model for TaskConfig.
type TaskConfig struct {
	Command        string  `json:"command"`
	TimeoutSeconds *int    `json:"timeout_seconds,omitempty"`
	WorkingDir     *string `json:"working_dir,omitempty"`
}

// TaskExecution defines model for TaskExecution.
type TaskExecution struct {
	AgentId     openapi_types.UUID  `json:"agent_id"`
	CompletedAt *time.Time          `json:"completed_at"`
	Error       *string             `json:"error,omitempty"`
	ExitCode    *int                `json:"exit_code"`
	Id          openapi_types.UUID  `json:"id"`
	Output      *string             `json:"output,omitempty"`
	StartedAt   time.Time           `json:"started_at"`
	Status      TaskExecutionStatus `json:"status"`
	TaskId      openapi_types.UUID  `json:"task_id"`
}

// TaskExecutionStatus defines model for TaskExecution.Status.
type TaskExecutionStatus string

// Template defines model for Template.
type Template struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// TemplateTask defines model for TemplateTask.
type TemplateTask struct {
	Blocking   *bool              `json:"blocking,omitempty"`
	Config     TaskConfig         `json:"config"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	Order      int                `json:"order"`
	TemplateId openapi_types.UUID `json:"template_id"`
	Type       TemplateTaskType   `json:"type"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// TemplateTaskType defines model for TemplateTask.Type.
type TemplateTaskType string

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Blocking *bool       `json:"blocking,omitempty"`
	Config   *TaskConfig `json:"config,omitempty"`
	Name     *string     `json:"name,omitempty"`
}

// UpdateTemplateRequest defines model for UpdateTemplateRequest.
type UpdateTemplateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListDebugTasksByAgentParams defines parameters for ListDebugTasksByAgent.
type ListDebugTasksByAgentParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAgentExecutionsParams defines parameters for ListAgentExecutions.
type ListAgentExecutionsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAgentsByClusterParams defines parameters for ListAgentsByCluster.
type ListAgentsByClusterParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	ClusterId *openapi_types.UUID         `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
	AgentId   *openapi_types.UUID         `form:"agent_id,omitempty" json:"agent_id,omitempty"`
	TaskId    *openapi_types.UUID         `form:"task_id,omitempty" json:"task_id,omitempty"`
	Status    *ListExecutionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit     *Limit                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *Offset                     `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExecutionsParamsStatus defines parameters for ListExecutions.
type ListExecutionsParamsStatus string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	ClusterId      openapi_types.UUID `form:"cluster_id" json:"cluster_id"`
	IncludeDeleted *bool              `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
	Limit          *Limit             `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *Offset            `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTemplateTasksParams defines parameters for ListTemplateTasks.
type ListTemplateTasksParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = CreateClusterRequest

// ExportTemplateJSONRequestBody defines body for ExportTemplate for application/json ContentType.
type ExportTemplateJSONRequestBody = ExportTemplateRequest

// ImportTemplateJSONRequestBody defines body for ImportTemplate for application/json ContentType.
type ImportTemplateJSONRequestBody = ImportTemplateRequest

// CreateDebugTaskJSONRequestBody defines body for CreateDebugTask for application/json ContentType.
type CreateDebugTaskJSONRequestBody = CreateDebugTaskRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ReorderTasksJSONRequestBody defines body for ReorderTasks for application/json ContentType.
type ReorderTasksJSONRequestBody = ReorderTasksRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = UpdateTemplateRequest

// CreateTemplateTaskJSONRequestBody defines body for CreateTemplateTask for application/json ContentType.
type CreateTemplateTaskJSONRequestBody = CreateTemplateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List debug tasks for an agent
	// (GET /api/v1/agents/{agentId}/debug-tasks)
	ListDebugTasksByAgent(w http.ResponseWriter, r *http.Request, agentId openapi_types.UUID, params ListDebugTasksByAgentParams)
	// Delete agent
	// (DELETE /api/v1/agents/{id})
	DeleteAgent(w http.ResponseWriter, r *http.Request, id ID)
	// Get agent by ID
	// (GET /api/v1/agents/{id})
	GetAgent(w http.ResponseWriter, r *http.Request, id ID)
	// List executions for an agent
	// (GET /api/v1/agents/{id}/executions)
	ListAgentExecutions(w http.ResponseWriter, r *http.Request, id ID, params ListAgentExecutionsParams)
	// List all clusters
	// (GET /api/v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Create a new cluster
	// (POST /api/v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// List agents in a cluster
	// (GET /api/v1/clusters/{clusterId}/agents)
	ListAgentsByCluster(w http.ResponseWriter, r *http.Request, clusterId openapi_types.UUID, params ListAgentsByClusterParams)
	// Delete cluster
	// (DELETE /api/v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ID)
	// Get cluster by ID
	// (GET /api/v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ID)
	// Export cluster tasks to template
	// (POST /api/v1/clusters/{id}/export-template)
	ExportTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Import template to cluster
	// (POST /api/v1/clusters/{id}/import-template)
	ImportTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Create a debug task
	// (POST /api/v1/debug-tasks)
	CreateDebugTask(w http.ResponseWriter, r *http.Request)
	// Get debug task by ID
	// (GET /api/v1/debug-tasks/{id})
	GetDebugTask(w http.ResponseWriter, r *http.Request, id ID)
	// List all executions
	// (GET /api/v1/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams)
	// Get execution by ID
	// (GET /api/v1/executions/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id ID)
	// List tasks for a cluster
	// (GET /api/v1/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams)
	// Create a new task
	// (POST /api/v1/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// Reorder tasks
	// (POST /api/v1/tasks/reorder)
	ReorderTasks(w http.ResponseWriter, r *http.Request)
	// Delete task
	// (DELETE /api/v1/tasks/{id})
	DeleteTask(w http.ResponseWriter, r *http.Request, id ID)
	// Get task by ID
	// (GET /api/v1/tasks/{id})
	GetTask(w http.ResponseWriter, r *http.Request, id ID)
	// Update task
	// (PUT /api/v1/tasks/{id})
	UpdateTask(w http.ResponseWriter, r *http.Request, id ID)
	// Reset task executions
	// (POST /api/v1/tasks/{id}/reset-executions)
	ResetTaskExecutions(w http.ResponseWriter, r *http.Request, id ID)
	// List all templates
	// (GET /api/v1/templates)
	ListTemplates(w http.ResponseWriter, r *http.Request, params ListTemplatesParams)
	// Create a new template
	// (POST /api/v1/templates)
	CreateTemplate(w http.ResponseWriter, r *http.Request)
	// Delete template
	// (DELETE /api/v1/templates/{id})
	DeleteTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Get template by ID
	// (GET /api/v1/templates/{id})
	GetTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Update template
	// (PUT /api/v1/templates/{id})
	UpdateTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// List tasks in a template
	// (GET /api/v1/templates/{id}/tasks)
	ListTemplateTasks(w http.ResponseWriter, r *http.Request, id ID, params ListTemplateTasksParams)
	// Add a task to template
	// (POST /api/v1/templates/{id}/tasks)
	CreateTemplateTask(w http.ResponseWriter, r *http.Request, id ID)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List debug tasks for an agent
// (GET /api/v1/agents/{agentId}/debug-tasks)
func (_ Unimplemented) ListDebugTasksByAgent(w http.ResponseWriter, r *http.Request, agentId openapi_types.UUID, params ListDebugTasksByAgentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete agent
// (DELETE /api/v1/agents/{id})
func (_ Unimplemented) DeleteAgent(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get agent by ID
// (GET /api/v1/agents/{id})
func (_ Unimplemented) GetAgent(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List executions for an agent
// (GET /api/v1/agents/{id}/executions)
func (_ Unimplemented) ListAgentExecutions(w http.ResponseWriter, r *http.Request, id ID, params ListAgentExecutionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all clusters
// (GET /api/v1/clusters)
func (_ Unimplemented) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new cluster
// (POST /api/v1/clusters)
func (_ Unimplemented) CreateCluster(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List agents in a cluster
// (GET /api/v1/clusters/{clusterId}/agents)
func (_ Unimplemented) ListAgentsByCluster(w http.ResponseWriter, r *http.Request, clusterId openapi_types.UUID, params ListAgentsByClusterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete cluster
// (DELETE /api/v1/clusters/{id})
func (_ Unimplemented) DeleteCluster(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cluster by ID
// (GET /api/v1/clusters/{id})
func (_ Unimplemented) GetCluster(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export cluster tasks to template
// (POST /api/v1/clusters/{id}/export-template)
func (_ Unimplemented) ExportTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import template to cluster
// (POST /api/v1/clusters/{id}/import-template)
func (_ Unimplemented) ImportTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a debug task
// (POST /api/v1/debug-tasks)
func (_ Unimplemented) CreateDebugTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get debug task by ID
// (GET /api/v1/debug-tasks/{id})
func (_ Unimplemented) GetDebugTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all executions
// (GET /api/v1/executions)
func (_ Unimplemented) ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get execution by ID
// (GET /api/v1/executions/{id})
func (_ Unimplemented) GetExecution(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tasks for a cluster
// (GET /api/v1/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new task
// (POST /api/v1/tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder tasks
// (POST /api/v1/tasks/reorder)
func (_ Unimplemented) ReorderTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete task
// (DELETE /api/v1/tasks/{id})
func (_ Unimplemented) DeleteTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get task by ID
// (GET /api/v1/tasks/{id})
func (_ Unimplemented) GetTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update task
// (PUT /api/v1/tasks/{id})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset task executions
// (POST /api/v1/tasks/{id}/reset-executions)
func (_ Unimplemented) ResetTaskExecutions(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all templates
// (GET /api/v1/templates)
func (_ Unimplemented) ListTemplates(w http.ResponseWriter, r *http.Request, params ListTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new template
// (POST /api/v1/templates)
func (_ Unimplemented) CreateTemplate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete template
// (DELETE /api/v1/templates/{id})
func (_ Unimplemented) DeleteTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get template by ID
// (GET /api/v1/templates/{id})
func (_ Unimplemented) GetTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update template
// (PUT /api/v1/templates/{id})
func (_ Unimplemented) UpdateTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tasks in a template
// (GET /api/v1/templates/{id}/tasks)
func (_ Unimplemented) ListTemplateTasks(w http.ResponseWriter, r *http.Request, id ID, params ListTemplateTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a task to template
// (POST /api/v1/templates/{id}/tasks)
func (_ Unimplemented) CreateTemplateTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDebugTasksByAgent operation middleware
func (siw *ServerInterfaceWrapper) ListDebugTasksByAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDebugTasksByAgentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDebugTasksByAgent(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAgent operation middleware
func (siw *ServerInterfaceWrapper) DeleteAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgentExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListAgentExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentExecutionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentExecutions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgentsByCluster operation middleware
func (siw *ServerInterfaceWrapper) ListAgentsByCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "clusterId" -------------
	var clusterId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", chi.URLParam(r, "clusterId"), &clusterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "clusterId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsByClusterParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentsByCluster(w, r, clusterId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportTemplate operation middleware
func (siw *ServerInterfaceWrapper) ExportTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportTemplate operation middleware
func (siw *ServerInterfaceWrapper) ImportTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDebugTask operation middleware
func (siw *ServerInterfaceWrapper) CreateDebugTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDebugTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDebugTask operation middleware
func (siw *ServerInterfaceWrapper) GetDebugTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDebugTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	// ------------- Optional query parameter "agent_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "agent_id", r.URL.Query(), &params.AgentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Optional query parameter "task_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "task_id", r.URL.Query(), &params.TaskId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task_id", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Required query parameter "cluster_id" -------------

	if paramValue := r.URL.Query().Get("cluster_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cluster_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "cluster_id", r.URL.Query(), &params.ClusterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	// ------------- Optional query parameter "include_deleted" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_deleted", r.URL.Query(), &params.IncludeDeleted)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_deleted", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderTasks operation middleware
func (siw *ServerInterfaceWrapper) ReorderTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetTaskExecutions operation middleware
func (siw *ServerInterfaceWrapper) ResetTaskExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetTaskExecutions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplatesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplateTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTemplateTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplateTasksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplateTasks(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agents/{agentId}/debug-tasks", wrapper.ListDebugTasksByAgent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/agents/{id}", wrapper.DeleteAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agents/{id}", wrapper.GetAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agents/{id}/executions", wrapper.ListAgentExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters", wrapper.ListClusters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters", wrapper.CreateCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{clusterId}/agents", wrapper.ListAgentsByCluster)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/clusters/{id}", wrapper.DeleteCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{id}", wrapper.GetCluster)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters/{id}/export-template", wrapper.ExportTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters/{id}/import-template", wrapper.ImportTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/debug-tasks", wrapper.CreateDebugTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/debug-tasks/{id}", wrapper.GetDebugTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/executions", wrapper.ListExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/executions/{id}", wrapper.GetExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/reorder", wrapper.ReorderTasks)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tasks/{id}", wrapper.DeleteTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks/{id}", wrapper.GetTask)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/tasks/{id}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/{id}/reset-executions", wrapper.ResetTaskExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/templates", wrapper.ListTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/templates", wrapper.CreateTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/templates/{id}", wrapper.DeleteTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/templates/{id}", wrapper.GetTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/templates/{id}", wrapper.UpdateTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/templates/{id}/tasks", wrapper.ListTemplateTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/templates/{id}/tasks", wrapper.CreateTemplateTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc32/bOPL/Vwh+v49q7N7uAgu/tU1vL0D3uuj2norCYKSxza1EqiSVxgj8vx9IShRl",
	"UbJsya73mpc2McnhcH5+OEPnCcc8yzkDpiRePOGcCJKBAmF+u7vV/1KGFzgnaoMjzEgGeIFpgiMs4GtB",
	"BSR4oUQBEZbxBjKiV6y4yIjCC1wUZqba5nqVVIKyNd7tIvyOZlQ54l8LENuaemoGfYIJrEiRKrz4ZR7h",
	"jDzSrMjw4uVc/0ZZ+ZvbhzIFaxBmo/erlYTOnbgdDW7l054HaO+0BGTOmQQjrNck+QBfC5Bmt5gzBcz8",
	"SPI8pTFRlLPZX5Iz/Vm93/8LWOEF/r9ZrYiZHZWzt0Jw8aHcxG6ZgIwFzTUxvNB7IlFuuovwv7n6Jy9Y",
	"cjkGPoDkhYgBMa7QyuytJ5XrNflX65KLXPAchKJWWnFaSAViSZMBBhPhDZfK6uypPTiQRkqkWm6ACHUP",
	"RDWWJETBC0UzCK0TsKaaV0iWxyyTiqjCnBWYtqFPmMSKPui5lJU/fg75Ru1Xn6yjebLyJOF2aJ1sn+V6",
	"F37/F8TGVN5YmgHFCCDqyKM2bOJ0BXUquMiTI3kKibGUmnfABuWglMzcUlaedzdFduj41bkyyt4BW6uN",
	"H6w6ODZrulm6hfti/ZHIL51MEe13Q90r5llGbNzoZ8tRrdd0M9nL333K4y96Cz/mrkgqwdG75zwFwgyD",
	"x4WLmLMVXR+Kbpq/N3Zmn/XZD2o3hkeID3tuw2lL0zMrHHc9goMsT4mC0RY3ysYqLqZU4/fXy2BVOBc7",
	"m2+ZsTyFA6GNFWlK7lOocFabygkhG3RmD/IEj1QtY54Y2Xbs7VDQ4NjOC5UXKrhhO1HmwBI9GGFRMGZ/",
	"kkUcg9TZbkVoCnoT+YXmOSQDs2ggdHkp1JNhyBiaQKhlEN3SzEBKsh7gjJZEcO/HnAt1MCYoIr8sadKO",
	"D/i9+YGkiAhBtoivkJ6L7m4lUhyBIX+D7lYIslxtEReIZ1QpSCJE0tRMlogIKKdCcqMxjIJMDlJ9+YHZ",
	"3PxenmR5KIq5icPCWXN6SJL/ApKqTbcaPUt8JNoz9eovQXTRon2XDdNSxeQgv+k6IQ2n3X0eus7ZbZSR",
	"MSO5pJnVtDfFv1X5TFXEWktDHP5B1pRpR+tmLq2uhu1Yw91lrj2muCLpAHbtvMhdMkuaIWY/ABcJCJ0D",
	"ZKdCj0Qmvpee6kJ9SMPRDx0onM38FP5dkNdpV47xeXPstcRYR4c1DsMmU11tesCmZTKqtex0dNxVyFNZ",
	"2wd6II4+BC/UUkLMmbX7tri+caF5WyZUHI7zfRcPzeXbR4iLKqmMA24TgLPrAlpCja5ijAZnLkgdnwD9",
	"ENeEdA7IeYcMGkiZHJ8LH/3e7t39js4YF0oB5wzfR6G0i4d7n72ueH9SkP+PGR584T/rBX/Xzd/5yiN7",
	"O+qPKFvxqqBOYrNb2T34nYBUgqOPQDLcLo2//fMjevXHHVpxgTLCNPJdozJTywiZ4CUje72KEGEJgipz",
	"6UCmqEr9XX7XJCADpjRVHOEHENJu9fJmfjM3Jp0DIznFC/zTzfzmJxyZvo2RyYzkdPbwcma3nT2Z/++S",
	"3SyB+2L9wnCh560twNbiNB2DuwQv8DsqlauHyNdbW9SPGu2iT8FOUbnNuHZR2JrqzWe2nTRgYtkO2n3e",
	"a978Yz4/qmlC0vT9ypy5z87btx3N4p6tEkUal4E+gnVNKnQp2DPez4F+jVYk4itklG5NzzZsiiwjYlvN",
	"8IaN+RJmzdVk37VWti2PIWMP+LMmsW9gNNlZX9QYqm1St+bzDkM6oMW725AGf25XPgx5VN4VtMx+trNC",
	"9B21mWujNSVjOW4JwuyhZRCFfec3UFOecj5Zc89yFTCSSmqK0FSOldpvoKzI0P0W3d2GBBc2npkXDfvi",
	"kiHz1o+cx4v5OcL4qbm+QI2MMp4GA0GmHu2KMSELqRJor028qSYdaww/ipqr9u9IBTtlBNRL0rQer3Xq",
	"VKMDZs5lQIONrmuJHECq1zzZThb8gp3dXRNta5yya+n35XQ8VEpoC7gcQiV4t0F4fjgIe49Qmiqx50UE",
	"MfhWqSWslYCvzZ7KnzRetCH6cEiWr7e1Cg8DRbfDM1ScxMPL7D7Ov0tdh7zbjCDKEAmYU1/gHogMO21n",
	"KmxYudi06LDXtboR4rSnnV8yRE2IE0vhtZDioehk0WLOhXqh/PpeMLs026mnS3z6nBRu9F44KTnBBFRe",
	"jVVpCa0Ez5zJn5KjjraZCP8yoXkffN94xxQIRlIkQTyAQLaa37RcqzZnvPbWrDhStYlVhlwJsNeSbQN1",
	"gCU3273XZMnhZvggS56fjYluLTu7dr3rH9WWrcyc6Wozbme0DiveKyT2Yfu6jnVOdN96JHnhUOpV69ra",
	"uHUlthrkhxF7XYwbUn7ztOCQVhfq8NVwXbhjqOgmBB+1mFv4o1PYA0tUfdWp0NcSGu38oy4/IWp+l3Qs",
	"rbr3OppU3bF1lCZ8//d8D7x8QY+k6V4Lq/Qfz/473OdgqKqPcG2hak/AbeG5wSmjlRNdK1h1Cftwh88G",
	"uOMj1KhyTYg6ZXFaJLCsrubB72d1PDJ/dv2GZY71+M4WodccDEHEMlf2l3jPjgC/I/jrAi8fByA+Bt/2",
	"8V4AfFiMJ8C9YwmL2n/FeiZhhx7KDhJ3oCxniKDyVC0RlTuVZjlAPMOKjRNi4I4j1WXGUNWwQ9nd9cKr",
	"BO29Ju9yXyuVBSG3F0CKgAjqh0rXVPZoP5+6cMmjVwPl2689DVieB4cbU6ESIEG9aF5+uoKPtMY6skE/",
	"yM/qPZDhsBU7ZGVtQZQaOrOrdPTiJjfrud18qKg8Eo04SV9j8cxdgpRnEKGi2QFUVBd0z4iM/j5dhhOL",
	"sVdnHk14N7g54IxpKJYZ3Q84iGcqBZ3eOr1C9VRQrF8xPZBsWrnPL+trp5cmrlCVBlVWJ2shy2Yg7kGX",
	"V9hYCz+AvzTKHGJQDm3+oJ20ClefGOeHlOu87+g8P3udBqBOUjJzzVNbO/tfsGav5GeefB3MkkMA7rVd",
	"37v/7Ml3Qsed13nfwkbC5L+/bb5KEm2RWhTDXt1szJ+B6Os22T8Ugc+YQ/f+FEXg6H+CeKAxICqRZXi7",
	"d25LAsUbiP3STcm7jVBWbNax9qIVj0mKEniAlOfmW2V2Lo5wIVK8wBul8sVslup5Gy7V4tf5r3Pje+VO",
	"+xR9fhCwJOeUKVl3dUrGdKQOvyTM3Dfc6kXu6V97mf2aSmhR+fy0vcTUwUIrPpahOrig7rU9UPhm29Hl",
	"Oq+s1V7svVMI7em/KujY2aWSIM91MeTz7r8BAAD//+1lwzLJUQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
