// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentStatus.
const (
	AgentStatusActive   AgentStatus = "active"
	AgentStatusInactive AgentStatus = "inactive"
)

// Defines values for CreateTaskRequestType.
const (
	CreateTaskRequestTypeExec CreateTaskRequestType = "exec"
)

// Defines values for CreateTemplateTaskRequestType.
const (
	CreateTemplateTaskRequestTypeExec CreateTemplateTaskRequestType = "exec"
)

// Defines values for DebugTaskStatus.
const (
	DebugTaskStatusFailed  DebugTaskStatus = "failed"
	DebugTaskStatusPending DebugTaskStatus = "pending"
	DebugTaskStatusRunning DebugTaskStatus = "running"
	DebugTaskStatusSkipped DebugTaskStatus = "skipped"
	DebugTaskStatusSuccess DebugTaskStatus = "success"
)

// Defines values for TaskType.
const (
	TaskTypeExec TaskType = "exec"
)

// Defines values for TaskExecutionStatus.
const (
	TaskExecutionStatusFailed  TaskExecutionStatus = "failed"
	TaskExecutionStatusPending TaskExecutionStatus = "pending"
	TaskExecutionStatusRunning TaskExecutionStatus = "running"
	TaskExecutionStatusSkipped TaskExecutionStatus = "skipped"
	TaskExecutionStatusSuccess TaskExecutionStatus = "success"
)

// Defines values for TemplateTaskType.
const (
	TemplateTaskTypeExec TemplateTaskType = "exec"
)

// Defines values for ListExecutionsParamsStatus.
const (
	ListExecutionsParamsStatusFailed  ListExecutionsParamsStatus = "failed"
	ListExecutionsParamsStatusPending ListExecutionsParamsStatus = "pending"
	ListExecutionsParamsStatusRunning ListExecutionsParamsStatus = "running"
	ListExecutionsParamsStatusSkipped ListExecutionsParamsStatus = "skipped"
	ListExecutionsParamsStatusSuccess ListExecutionsParamsStatus = "success"
)

// Agent defines model for Agent.
type Agent struct {
	ClusterId     openapi_types.UUID `json:"cluster_id"`
	Hostname      string             `json:"hostname"`
	Id            openapi_types.UUID `json:"id"`
	LastHeartbeat time.Time          `json:"last_heartbeat"`
	RegisteredAt  time.Time          `json:"registered_at"`
	Status        AgentStatus        `json:"status"`
}

// AgentStatus defines model for Agent.Status.
type AgentStatus string

// Cluster defines model for Cluster.
type Cluster struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// CreateClusterRequest defines model for CreateClusterRequest.
type CreateClusterRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateDebugTaskRequest defines model for CreateDebugTaskRequest.
type CreateDebugTaskRequest struct {
	AgentId openapi_types.UUID `json:"agent_id"`
	Command string             `json:"command"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Blocking  *bool                 `json:"blocking,omitempty"`
	ClusterId openapi_types.UUID    `json:"cluster_id"`
	Config    TaskConfig            `json:"config"`
	Name      string                `json:"name"`
	Type      CreateTaskRequestType `json:"type"`
}

// CreateTaskRequestType defines model for CreateTaskRequest.Type.
type CreateTaskRequestType string

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateTemplateTaskRequest defines model for CreateTemplateTaskRequest.
type CreateTemplateTaskRequest struct {
	Blocking *bool                         `json:"blocking,omitempty"`
	Config   TaskConfig                    `json:"config"`
	Name     string                        `json:"name"`
	Type     CreateTemplateTaskRequestType `json:"type"`
}

// CreateTemplateTaskRequestType defines model for CreateTemplateTaskRequest.Type.
type CreateTemplateTaskRequestType string

// DebugTask defines model for DebugTask.
type DebugTask struct {
	AgentId     openapi_types.UUID `json:"agent_id"`
	Command     string             `json:"command"`
	CompletedAt *time.Time         `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	Error       *string            `json:"error,omitempty"`
	ExitCode    *int               `json:"exit_code"`
	Id          openapi_types.UUID `json:"id"`
	Output      *string            `json:"output,omitempty"`
	Status      DebugTaskStatus    `json:"status"`
}

// DebugTaskStatus defines model for DebugTask.Status.
type DebugTaskStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// ExportTemplateRequest defines model for ExportTemplateRequest.
type ExportTemplateRequest struct {
	TemplateDescription *string `json:"template_description,omitempty"`
	TemplateName        string  `json:"template_name"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status *string `json:"status,omitempty"`
}

// ImportTemplateRequest defines model for ImportTemplateRequest.
type ImportTemplateRequest struct {
	TemplateId openapi_types.UUID `json:"template_id"`
}

// ImportTemplateResponse defines model for ImportTemplateResponse.
type ImportTemplateResponse struct {
	Message       string `json:"message"`
	TasksImported int    `json:"tasks_imported"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
	Total  int `json:"total"`
}

// ReorderTasksRequest defines model for ReorderTasksRequest.
type ReorderTasksRequest struct {
	ClusterId openapi_types.UUID   `json:"cluster_id"`
	TaskIds   []openapi_types.UUID `json:"task_ids"`
}

// Task defines model for Task.
type Task struct {
	Blocking  bool               `json:"blocking"`
	ClusterId openapi_types.UUID `json:"cluster_id"`
	Config    TaskConfig         `json:"config"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt *time.Time         `json:"deleted_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Order     int                `json:"order"`
	Type      TaskType           `json:"type"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// TaskType defines model for Task.Type.
type TaskType string

// TaskConfig defines model for TaskConfig.
type TaskConfig struct {
	Command        string  `json:"command"`
	TimeoutSeconds *int    `json:"timeout_seconds,omitempty"`
	WorkingDir     *string `json:"working_dir,omitempty"`
}

// TaskExecution defines model for TaskExecution.
type TaskExecution struct {
	AgentId     openapi_types.UUID  `json:"agent_id"`
	CompletedAt *time.Time          `json:"completed_at"`
	Error       *string             `json:"error,omitempty"`
	ExitCode    *int                `json:"exit_code"`
	Id          openapi_types.UUID  `json:"id"`
	Output      *string             `json:"output,omitempty"`
	StartedAt   time.Time           `json:"started_at"`
	Status      TaskExecutionStatus `json:"status"`
	TaskId      openapi_types.UUID  `json:"task_id"`
}

// TaskExecutionStatus defines model for TaskExecution.Status.
type TaskExecutionStatus string

// Template defines model for Template.
type Template struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// TemplateTask defines model for TemplateTask.
type TemplateTask struct {
	Blocking   *bool              `json:"blocking,omitempty"`
	Config     TaskConfig         `json:"config"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	Order      int                `json:"order"`
	TemplateId openapi_types.UUID `json:"template_id"`
	Type       TemplateTaskType   `json:"type"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// TemplateTaskType defines model for TemplateTask.Type.
type TemplateTaskType string

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Blocking *bool       `json:"blocking,omitempty"`
	Config   *TaskConfig `json:"config,omitempty"`
	Name     *string     `json:"name,omitempty"`
}

// UpdateTemplateRequest defines model for UpdateTemplateRequest.
type UpdateTemplateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListDebugTasksByAgentParams defines parameters for ListDebugTasksByAgent.
type ListDebugTasksByAgentParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAgentExecutionsParams defines parameters for ListAgentExecutions.
type ListAgentExecutionsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAgentsByClusterParams defines parameters for ListAgentsByCluster.
type ListAgentsByClusterParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExecutionsParams defines parameters for ListExecutions.
type ListExecutionsParams struct {
	ClusterId *openapi_types.UUID         `form:"cluster_id,omitempty" json:"cluster_id,omitempty"`
	AgentId   *openapi_types.UUID         `form:"agent_id,omitempty" json:"agent_id,omitempty"`
	TaskId    *openapi_types.UUID         `form:"task_id,omitempty" json:"task_id,omitempty"`
	Status    *ListExecutionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit     *Limit                      `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *Offset                     `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListExecutionsParamsStatus defines parameters for ListExecutions.
type ListExecutionsParamsStatus string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	ClusterId      openapi_types.UUID `form:"cluster_id" json:"cluster_id"`
	IncludeDeleted *bool              `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
	Limit          *Limit             `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *Offset            `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTemplateTasksParams defines parameters for ListTemplateTasks.
type ListTemplateTasksParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = CreateClusterRequest

// ExportTemplateJSONRequestBody defines body for ExportTemplate for application/json ContentType.
type ExportTemplateJSONRequestBody = ExportTemplateRequest

// ImportTemplateJSONRequestBody defines body for ImportTemplate for application/json ContentType.
type ImportTemplateJSONRequestBody = ImportTemplateRequest

// CreateDebugTaskJSONRequestBody defines body for CreateDebugTask for application/json ContentType.
type CreateDebugTaskJSONRequestBody = CreateDebugTaskRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ReorderTasksJSONRequestBody defines body for ReorderTasks for application/json ContentType.
type ReorderTasksJSONRequestBody = ReorderTasksRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = UpdateTemplateRequest

// CreateTemplateTaskJSONRequestBody defines body for CreateTemplateTask for application/json ContentType.
type CreateTemplateTaskJSONRequestBody = CreateTemplateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List debug tasks for an agent
	// (GET /api/v1/agents/{agentId}/debug-tasks)
	ListDebugTasksByAgent(w http.ResponseWriter, r *http.Request, agentId openapi_types.UUID, params ListDebugTasksByAgentParams)
	// Delete agent
	// (DELETE /api/v1/agents/{id})
	DeleteAgent(w http.ResponseWriter, r *http.Request, id ID)
	// Get agent by ID
	// (GET /api/v1/agents/{id})
	GetAgent(w http.ResponseWriter, r *http.Request, id ID)
	// List executions for an agent
	// (GET /api/v1/agents/{id}/executions)
	ListAgentExecutions(w http.ResponseWriter, r *http.Request, id ID, params ListAgentExecutionsParams)
	// List all clusters
	// (GET /api/v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Create a new cluster
	// (POST /api/v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// List agents in a cluster
	// (GET /api/v1/clusters/{clusterId}/agents)
	ListAgentsByCluster(w http.ResponseWriter, r *http.Request, clusterId openapi_types.UUID, params ListAgentsByClusterParams)
	// Delete cluster
	// (DELETE /api/v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ID)
	// Get cluster by ID
	// (GET /api/v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ID)
	// Export cluster tasks to template
	// (POST /api/v1/clusters/{id}/export-template)
	ExportTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Import template to cluster
	// (POST /api/v1/clusters/{id}/import-template)
	ImportTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Create a debug task
	// (POST /api/v1/debug-tasks)
	CreateDebugTask(w http.ResponseWriter, r *http.Request)
	// Get debug task by ID
	// (GET /api/v1/debug-tasks/{id})
	GetDebugTask(w http.ResponseWriter, r *http.Request, id ID)
	// List all executions
	// (GET /api/v1/executions)
	ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams)
	// Get execution by ID
	// (GET /api/v1/executions/{id})
	GetExecution(w http.ResponseWriter, r *http.Request, id ID)
	// List tasks for a cluster
	// (GET /api/v1/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams)
	// Create a new task
	// (POST /api/v1/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// Reorder tasks
	// (POST /api/v1/tasks/reorder)
	ReorderTasks(w http.ResponseWriter, r *http.Request)
	// Delete task
	// (DELETE /api/v1/tasks/{id})
	DeleteTask(w http.ResponseWriter, r *http.Request, id ID)
	// Get task by ID
	// (GET /api/v1/tasks/{id})
	GetTask(w http.ResponseWriter, r *http.Request, id ID)
	// Update task
	// (PUT /api/v1/tasks/{id})
	UpdateTask(w http.ResponseWriter, r *http.Request, id ID)
	// Reset task executions
	// (POST /api/v1/tasks/{id}/reset-executions)
	ResetTaskExecutions(w http.ResponseWriter, r *http.Request, id ID)
	// List all templates
	// (GET /api/v1/templates)
	ListTemplates(w http.ResponseWriter, r *http.Request, params ListTemplatesParams)
	// Create a new template
	// (POST /api/v1/templates)
	CreateTemplate(w http.ResponseWriter, r *http.Request)
	// Delete template
	// (DELETE /api/v1/templates/{id})
	DeleteTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Get template by ID
	// (GET /api/v1/templates/{id})
	GetTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// Update template
	// (PUT /api/v1/templates/{id})
	UpdateTemplate(w http.ResponseWriter, r *http.Request, id ID)
	// List tasks in a template
	// (GET /api/v1/templates/{id}/tasks)
	ListTemplateTasks(w http.ResponseWriter, r *http.Request, id ID, params ListTemplateTasksParams)
	// Add a task to template
	// (POST /api/v1/templates/{id}/tasks)
	CreateTemplateTask(w http.ResponseWriter, r *http.Request, id ID)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List debug tasks for an agent
// (GET /api/v1/agents/{agentId}/debug-tasks)
func (_ Unimplemented) ListDebugTasksByAgent(w http.ResponseWriter, r *http.Request, agentId openapi_types.UUID, params ListDebugTasksByAgentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete agent
// (DELETE /api/v1/agents/{id})
func (_ Unimplemented) DeleteAgent(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get agent by ID
// (GET /api/v1/agents/{id})
func (_ Unimplemented) GetAgent(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List executions for an agent
// (GET /api/v1/agents/{id}/executions)
func (_ Unimplemented) ListAgentExecutions(w http.ResponseWriter, r *http.Request, id ID, params ListAgentExecutionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all clusters
// (GET /api/v1/clusters)
func (_ Unimplemented) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new cluster
// (POST /api/v1/clusters)
func (_ Unimplemented) CreateCluster(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List agents in a cluster
// (GET /api/v1/clusters/{clusterId}/agents)
func (_ Unimplemented) ListAgentsByCluster(w http.ResponseWriter, r *http.Request, clusterId openapi_types.UUID, params ListAgentsByClusterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete cluster
// (DELETE /api/v1/clusters/{id})
func (_ Unimplemented) DeleteCluster(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cluster by ID
// (GET /api/v1/clusters/{id})
func (_ Unimplemented) GetCluster(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export cluster tasks to template
// (POST /api/v1/clusters/{id}/export-template)
func (_ Unimplemented) ExportTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Import template to cluster
// (POST /api/v1/clusters/{id}/import-template)
func (_ Unimplemented) ImportTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a debug task
// (POST /api/v1/debug-tasks)
func (_ Unimplemented) CreateDebugTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get debug task by ID
// (GET /api/v1/debug-tasks/{id})
func (_ Unimplemented) GetDebugTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all executions
// (GET /api/v1/executions)
func (_ Unimplemented) ListExecutions(w http.ResponseWriter, r *http.Request, params ListExecutionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get execution by ID
// (GET /api/v1/executions/{id})
func (_ Unimplemented) GetExecution(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tasks for a cluster
// (GET /api/v1/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new task
// (POST /api/v1/tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder tasks
// (POST /api/v1/tasks/reorder)
func (_ Unimplemented) ReorderTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete task
// (DELETE /api/v1/tasks/{id})
func (_ Unimplemented) DeleteTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get task by ID
// (GET /api/v1/tasks/{id})
func (_ Unimplemented) GetTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update task
// (PUT /api/v1/tasks/{id})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset task executions
// (POST /api/v1/tasks/{id}/reset-executions)
func (_ Unimplemented) ResetTaskExecutions(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all templates
// (GET /api/v1/templates)
func (_ Unimplemented) ListTemplates(w http.ResponseWriter, r *http.Request, params ListTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new template
// (POST /api/v1/templates)
func (_ Unimplemented) CreateTemplate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete template
// (DELETE /api/v1/templates/{id})
func (_ Unimplemented) DeleteTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get template by ID
// (GET /api/v1/templates/{id})
func (_ Unimplemented) GetTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update template
// (PUT /api/v1/templates/{id})
func (_ Unimplemented) UpdateTemplate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tasks in a template
// (GET /api/v1/templates/{id}/tasks)
func (_ Unimplemented) ListTemplateTasks(w http.ResponseWriter, r *http.Request, id ID, params ListTemplateTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a task to template
// (POST /api/v1/templates/{id}/tasks)
func (_ Unimplemented) CreateTemplateTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDebugTasksByAgent operation middleware
func (siw *ServerInterfaceWrapper) ListDebugTasksByAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDebugTasksByAgentParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDebugTasksByAgent(w, r, agentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAgent operation middleware
func (siw *ServerInterfaceWrapper) DeleteAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgentExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListAgentExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentExecutionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentExecutions(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgentsByCluster operation middleware
func (siw *ServerInterfaceWrapper) ListAgentsByCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "clusterId" -------------
	var clusterId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", chi.URLParam(r, "clusterId"), &clusterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "clusterId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsByClusterParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentsByCluster(w, r, clusterId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportTemplate operation middleware
func (siw *ServerInterfaceWrapper) ExportTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportTemplate operation middleware
func (siw *ServerInterfaceWrapper) ImportTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDebugTask operation middleware
func (siw *ServerInterfaceWrapper) CreateDebugTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDebugTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDebugTask operation middleware
func (siw *ServerInterfaceWrapper) GetDebugTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDebugTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutions operation middleware
func (siw *ServerInterfaceWrapper) ListExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionsParams

	// ------------- Optional query parameter "cluster_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "cluster_id", r.URL.Query(), &params.ClusterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	// ------------- Optional query parameter "agent_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "agent_id", r.URL.Query(), &params.AgentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		return
	}

	// ------------- Optional query parameter "task_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "task_id", r.URL.Query(), &params.TaskId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task_id", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecution operation middleware
func (siw *ServerInterfaceWrapper) GetExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecution(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Required query parameter "cluster_id" -------------

	if paramValue := r.URL.Query().Get("cluster_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cluster_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "cluster_id", r.URL.Query(), &params.ClusterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	// ------------- Optional query parameter "include_deleted" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_deleted", r.URL.Query(), &params.IncludeDeleted)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_deleted", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderTasks operation middleware
func (siw *ServerInterfaceWrapper) ReorderTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetTaskExecutions operation middleware
func (siw *ServerInterfaceWrapper) ResetTaskExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetTaskExecutions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplatesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplates(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTemplateTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTemplateTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplateTasksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTemplateTasks(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTemplateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTemplateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agents/{agentId}/debug-tasks", wrapper.ListDebugTasksByAgent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/agents/{id}", wrapper.DeleteAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agents/{id}", wrapper.GetAgent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/agents/{id}/executions", wrapper.ListAgentExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters", wrapper.ListClusters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters", wrapper.CreateCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{clusterId}/agents", wrapper.ListAgentsByCluster)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/clusters/{id}", wrapper.DeleteCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{id}", wrapper.GetCluster)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters/{id}/export-template", wrapper.ExportTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters/{id}/import-template", wrapper.ImportTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/debug-tasks", wrapper.CreateDebugTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/debug-tasks/{id}", wrapper.GetDebugTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/executions", wrapper.ListExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/executions/{id}", wrapper.GetExecution)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/reorder", wrapper.ReorderTasks)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tasks/{id}", wrapper.DeleteTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks/{id}", wrapper.GetTask)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/tasks/{id}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/{id}/reset-executions", wrapper.ResetTaskExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/templates", wrapper.ListTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/templates", wrapper.CreateTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/templates/{id}", wrapper.DeleteTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/templates/{id}", wrapper.GetTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/templates/{id}", wrapper.UpdateTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/templates/{id}/tasks", wrapper.ListTemplateTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/templates/{id}/tasks", wrapper.CreateTemplateTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcUW/bOBL+KwLvHtXavd0FFn5rm95egO7topt7KgKDkcY2NxKpklSaIPB/P5CUKMoi",
	"ZdmSXe82L21iicPhzMeZjzN0nlHC8oJRoFKgxTMqMMc5SOD6t+sr9S+haIEKLDcoRhTngBaIpChGHL6U",
	"hEOKFpKXECORbCDHasSK8RxLtEBlqd+UT4UaJSQndI222xh9JDmRVviXEvhTIz3TD12BKaxwmUm0+Gke",
	"oxw/krzM0eLNXP1GaPWbnYdQCWvgeqLfVisBwZmYeeqdypU998jeKguIglEB2ljvcPoJvpQg9GwJoxKo",
	"/hEXRUYSLAmjsz8Fo+qzZr5/clihBfrHrHHEzDwVsw+cM/6pmsRMmYJIOCmUMLRQc0a8mnQbo/8y+W9W",
	"0vR8CnwCwUqeQESZjFZ6bvVSNV6Jf7uutCg4K4BLYqyVZKWQwJckHQCYGG2YkMZnz92HA2VkWMjlBjCX",
	"d4Bla0iKJbySJAffOA5ronSFdHnIMCGxLPVagSoMfUY4keRBvUto9eOtb280++qz2WiOrRxL2Bk6K9tV",
	"uZmF3f0JiYbKeyPT4xgOWB641BYmjndQ0MFlkR6ok8+MldWcBbYke62k361s5ezutsn2Lb9eV07oR6Br",
	"uXGDVUBjPSas0hXclesbLO6DSmG174Zur4TlOTZxo18tK7UZE1ayV7+7jCX3ago35q5wJsDKu2MsA0y1",
	"goeFi4TRFVnvi25Kv/fmzT70mQ+abQyPkOzfua1NW0FPj7Da9RgO8iLDEkYjbhTGai2mdOO398tgV9gt",
	"drK9pZ8VGewJbbTMMnyXQc2zulKOCNmgMrtXJ3gkcpmwVNs2MLdlQYNjOytlUUrvhN1EWQBN1cMY8ZJS",
	"85MokwSEynYrTDJQk4h7UhSQDsyintDlpFDHhj4wtIlQBxBha+YgBF4P2IxGhHfux4JxuTcmyOqF5b7g",
	"YF8cFiXar/sU/A/gTG7C1nEc/IgV4NXoe2/S7si+zg9b/CA4hlZI/NlsV4fQOsO+jpHE4l4siZYEbjBw",
	"DyuuUrWwzlCfhr/jNaEKv2HlsvrE1d3CzJ6Rus8kkzgboK55L7Znt0qmT9lPwHgKXIVWEXTogQlf2WhJ",
	"Uj2USMjFsFHmA8w5fupP4Fa+b0H+JOFmxm9CaI5j8uPT0Vi2r9ERQOOwlD/ViaGHwxkl48bL1keHnTAc",
	"l3X3QA9zUItgpVwKSBg1uO+a6yvjSrdlSvj+ON/H55WWHx4hKeukMo4PTcB5Lou/cDm6ODCa89ggdXgC",
	"dENcmylZfuQs0guQKjm+1BP6d7tzpDo4Y5wpBZwyfB/E0s4e7l31QvH+qCD/P/148Dn6pOfmbVi/01Ud",
	"dmZUHxG6YnWdGid6tqoo/ysGITmLbgDnqFtx/vDHTfT29+toxXiUY6qY7zqqMrWIIx28RBxp1hxHmKYR",
	"1JlLBTJJZObO8qsSATlQqaSiGD0AF2aqN6/nr+ca0gVQXBC0QD+8nr/+AcW6HaJtMsMFmT28mZlpZ8/6",
	"/+t0O0vhrly/0lqo99aGYCtz6kL8dYoW6CMR0pYZxLsnUyuPW12Yz94GTDXNuC6MH03N5DPTpRnwYtVl",
	"2d7u9ET+NZ8f1IvAWfbbSq+5D+fd045ScQerWOLWYaBPYFPq8R0KdsB762mDKEdGbBVppxvomT5ImeeY",
	"P9VvOI81fDE1cNXZd62cbapOkcYDulUidgFG0q3Zi4pDdSF1pT8PAGmPF6+vfB78sbP1TU8nqs4KymY/",
	"mrd88q20me1OtS1jNO4YQs+hbBD7984vIKdc5XyynpnRygOS2moSk0yMtdovII3Jorun6PrKZzg/eGZO",
	"NOyLS1rMBzdyHm7mlwjjpubmADUyyjge9ASZ5mkoxvgQUifQXky8r186FAzfi5vrrupIB1tneNyLs6x5",
	"3vjUukYFzIIJjwdbzcyKOYCQ71j6NFnw8zZMt222rXjKtuPfN9PpUDuha+DqUVSRdxOE5/uDsHO3o+0S",
	"s94IRxS+1m7xe8Wz12bP1U+KL5oQvT8ki3dPjQv3E0U7wwtVnGSHV9l93P6ufO3b3fpJRGiEPXDqC9wD",
	"mWEQO1Nxw3qLTcsOe7dWmCFOu9r5OUPUhDyxMl6HKe6LToYtFozLV9Kt73mzS7tLebzFp89J/v7pmZOS",
	"NYzH5fWzOi1FK85yC/ljctTBmInRTxPCe++1wWsqgVOcRQL4A/DIVPPbyDVus+A1p2bJItlArAZybcBe",
	"JJsG6gAkt9u9l4RkfzN8EJLnJ1Mi7GWLa9u7/l6xbGxmoatg3M1oARTvFBL7uH1Txzolu+/cPTxzKHWq",
	"dV1vXNkSW0Py/Yy9KcYNKb85XrBMK8Q6XDdcFu8YaroJyUdj5g7/CBp7YImqrzrlu+3faucfdPjxSXO7",
	"pGNlNb3X0aKajq2VNOG1updz4PkLejjLdlpY1f5x8B/YPntDVbOESwtVOwbuGs8+nDJaWdN1glXI2Ps7",
	"fCbAHR6hRpVrfNIJTbIyhWV9NPd+7Slwd/tl67eQOXbHB1uETnPQRxGrXNlf4j05A/yG5C9EXm4GMD4K",
	"X3f5nod8GI7Hwd5j8ZvavcV6ImP7LsoOMrenLKeFRNWqOiaqZqpgOcA8w4qNE3LgwJKaMqOvahhwdrhe",
	"eJGkvRfyNvd1UpmXcjsBpPSYoLmodEllj+71qTOXPHo9UN392vGA0XlwuNEVKg4C5Kv24ScUfIQB68gG",
	"/aB91swRaQ07sUPUaPOyVN+abaWjlzfZt17azfuKyiPZiLX0JRbP7CFIOoDwFc32sKKmoHtCZvTX6TIc",
	"WYy9OHi06d3g5oAF01AuM7ofsJfP1A46vnV6ge6pqVi/Y3oo2bR2n593rx1fmrhAV2pWWa+swyzbgbiH",
	"XV5gY81/Af7cLHMIoCzb/E47aTWvPjLODynXOd/Rebn2Og1BnaRkZpunpnb2d0CzU/LTV772ZskhBPfS",
	"ju/hvybyjdhx8DjvImwkTf7rY/NtmipEKlMMu3Wz0X8Goq/bZP5QBDphDt35UxSepf8B/IEkEBERGYWf",
	"dtZtRETJBhK3dFPpbiKUMZvZWDvRiiU4i1J4gIwV+ltl5l0Uo5JnaIE2UhaL2SxT722YkIuf5z/P9d6r",
	"ZtqV6OoTAU0LRqgUTVenUkxFav9Nwtx+w60ZZK/+dYeZr6n4BlXXT7tDdB3MN+KmCtXeAU2v7YHAV9OO",
	"rsY5Za3uYOeegm9O91ZBYGabSrw6N8WQ2+3/AwAA///Rih9LIFEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
