// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentStatus.
const (
	AgentStatusActive   AgentStatus = "active"
	AgentStatusInactive AgentStatus = "inactive"
)

// Defines values for CreateTaskRequestType.
const (
	CreateTaskRequestTypeExec CreateTaskRequestType = "exec"
)

// Defines values for TaskType.
const (
	TaskTypeExec TaskType = "exec"
)

// Agent defines model for Agent.
type Agent struct {
	ClusterId     openapi_types.UUID `json:"cluster_id"`
	Hostname      string             `json:"hostname"`
	Id            openapi_types.UUID `json:"id"`
	LastHeartbeat *time.Time         `json:"last_heartbeat,omitempty"`
	RegisteredAt  *time.Time         `json:"registered_at,omitempty"`
	Status        AgentStatus        `json:"status"`
}

// AgentStatus defines model for Agent.Status.
type AgentStatus string

// Cluster defines model for Cluster.
type Cluster struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// CreateClusterRequest defines model for CreateClusterRequest.
type CreateClusterRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Blocking  *bool                 `json:"blocking,omitempty"`
	ClusterId openapi_types.UUID    `json:"cluster_id"`
	Config    TaskConfig            `json:"config"`
	Name      string                `json:"name"`
	Type      CreateTaskRequestType `json:"type"`
}

// CreateTaskRequestType defines model for CreateTaskRequest.Type.
type CreateTaskRequestType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status *string `json:"status,omitempty"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
	Total  int `json:"total"`
}

// ReorderTasksRequest defines model for ReorderTasksRequest.
type ReorderTasksRequest struct {
	ClusterId openapi_types.UUID   `json:"cluster_id"`
	TaskIds   []openapi_types.UUID `json:"task_ids"`
}

// Task defines model for Task.
type Task struct {
	Blocking  bool               `json:"blocking"`
	ClusterId openapi_types.UUID `json:"cluster_id"`
	Config    TaskConfig         `json:"config"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Order     int                `json:"order"`
	Type      TaskType           `json:"type"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// TaskType defines model for Task.Type.
type TaskType string

// TaskConfig defines model for TaskConfig.
type TaskConfig struct {
	Command        string  `json:"command"`
	TimeoutSeconds *int    `json:"timeout_seconds,omitempty"`
	WorkingDir     *string `json:"working_dir,omitempty"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Blocking *bool       `json:"blocking,omitempty"`
	Config   *TaskConfig `json:"config,omitempty"`
	Name     *string     `json:"name,omitempty"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAgentsByClusterParams defines parameters for ListAgentsByCluster.
type ListAgentsByClusterParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	ClusterId      openapi_types.UUID `form:"cluster_id" json:"cluster_id"`
	IncludeDeleted *bool              `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
	Limit          *Limit             `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *Offset            `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = CreateClusterRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ReorderTasksJSONRequestBody defines body for ReorderTasks for application/json ContentType.
type ReorderTasksJSONRequestBody = ReorderTasksRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all clusters
	// (GET /api/v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Create a new cluster
	// (POST /api/v1/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// List agents in a cluster
	// (GET /api/v1/clusters/{clusterId}/agents)
	ListAgentsByCluster(w http.ResponseWriter, r *http.Request, clusterId openapi_types.UUID, params ListAgentsByClusterParams)
	// Delete cluster
	// (DELETE /api/v1/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ID)
	// Get cluster by ID
	// (GET /api/v1/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ID)
	// List tasks for a cluster
	// (GET /api/v1/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams)
	// Create a new task
	// (POST /api/v1/tasks)
	CreateTask(w http.ResponseWriter, r *http.Request)
	// Reorder tasks
	// (POST /api/v1/tasks/reorder)
	ReorderTasks(w http.ResponseWriter, r *http.Request)
	// Delete task
	// (DELETE /api/v1/tasks/{id})
	DeleteTask(w http.ResponseWriter, r *http.Request, id ID)
	// Get task by ID
	// (GET /api/v1/tasks/{id})
	GetTask(w http.ResponseWriter, r *http.Request, id ID)
	// Update task
	// (PUT /api/v1/tasks/{id})
	UpdateTask(w http.ResponseWriter, r *http.Request, id ID)
	// Reset task executions
	// (POST /api/v1/tasks/{id}/reset-executions)
	ResetTaskExecutions(w http.ResponseWriter, r *http.Request, id ID)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all clusters
// (GET /api/v1/clusters)
func (_ Unimplemented) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new cluster
// (POST /api/v1/clusters)
func (_ Unimplemented) CreateCluster(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List agents in a cluster
// (GET /api/v1/clusters/{clusterId}/agents)
func (_ Unimplemented) ListAgentsByCluster(w http.ResponseWriter, r *http.Request, clusterId openapi_types.UUID, params ListAgentsByClusterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete cluster
// (DELETE /api/v1/clusters/{id})
func (_ Unimplemented) DeleteCluster(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cluster by ID
// (GET /api/v1/clusters/{id})
func (_ Unimplemented) GetCluster(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tasks for a cluster
// (GET /api/v1/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new task
// (POST /api/v1/tasks)
func (_ Unimplemented) CreateTask(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reorder tasks
// (POST /api/v1/tasks/reorder)
func (_ Unimplemented) ReorderTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete task
// (DELETE /api/v1/tasks/{id})
func (_ Unimplemented) DeleteTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get task by ID
// (GET /api/v1/tasks/{id})
func (_ Unimplemented) GetTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update task
// (PUT /api/v1/tasks/{id})
func (_ Unimplemented) UpdateTask(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset task executions
// (POST /api/v1/tasks/{id}/reset-executions)
func (_ Unimplemented) ResetTaskExecutions(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgentsByCluster operation middleware
func (siw *ServerInterfaceWrapper) ListAgentsByCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "clusterId" -------------
	var clusterId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", chi.URLParam(r, "clusterId"), &clusterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "clusterId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsByClusterParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgentsByCluster(w, r, clusterId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Required query parameter "cluster_id" -------------

	if paramValue := r.URL.Query().Get("cluster_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cluster_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "cluster_id", r.URL.Query(), &params.ClusterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_id", Err: err})
		return
	}

	// ------------- Optional query parameter "include_deleted" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_deleted", r.URL.Query(), &params.IncludeDeleted)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_deleted", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTask operation middleware
func (siw *ServerInterfaceWrapper) CreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderTasks operation middleware
func (siw *ServerInterfaceWrapper) ReorderTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DeleteTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTask operation middleware
func (siw *ServerInterfaceWrapper) UpdateTask(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetTaskExecutions operation middleware
func (siw *ServerInterfaceWrapper) ResetTaskExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetTaskExecutions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters", wrapper.ListClusters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters", wrapper.CreateCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{clusterId}/agents", wrapper.ListAgentsByCluster)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/clusters/{id}", wrapper.DeleteCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{id}", wrapper.GetCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks", wrapper.ListTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks", wrapper.CreateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/reorder", wrapper.ReorderTasks)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tasks/{id}", wrapper.DeleteTask)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tasks/{id}", wrapper.GetTask)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/tasks/{id}", wrapper.UpdateTask)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tasks/{id}/reset-executions", wrapper.ResetTaskExecutions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYW2/buBL+KwTPeVQj57QHKPTWNt1ugHZbpN2nIjAYaWyzkUiVHLk1Av33BS+6U7bT",
	"ONmXvgSxyLnwm2+GM7yjqSxKKUCgpskdLZliBSAo++vywvzlgia0ZLihERWsAJpQntGIKvhecQUZTVBV",
	"EFGdbqBgRmIlVcGQJrSq7E7clUZKo+JiTes6ou95wbFV/r0Cteu053axrzCDFatypMn/FxEt2E9eVAVN",
	"zhfmFxf+V2uHC4Q1KGvo42qlYdaSdKtBU33di4Du2iCgSyk0WLBes+wKvlegrbVUCgRh/2VlmfOUIZci",
	"/qalMN86e/9VsKIJ/U/cBSJ2qzp+q5RUV96IM5mBThUvjTKaGJtEeaN1RP+S+IesRPZ0DlyBlpVKgQiJ",
	"ZGVtm01e3qh/tfZelEqWoJA7tNK80ghqybMjCBPRjdToYnY3XTxSR840LjfAFN4Aw4FIxhCeIS8gJKdg",
	"zY2vkC3vI6aRYWXPCsJw6CtlKfKt2cuF//c6lBtdXn11idbDqodEa6FTIm++QWqZ8MaJBHBXwPCeJxmE",
	"/Nfxn41fVWb39CmEkgeld8CB5iBKdq/Hqpe8Q8gOHb85V8HFexBr3PRr0YzHVmbepS9M3876c5PL9NYo",
	"7VerFcs1tPpupMyBCaPwnomWSrHi60N1wfj3xu3cF1j3oUsA+AnpYc4P6O6jaiVa70LADUvVBDQwywEn",
	"R7bdtpD+P4HluJk30Ev3n6wocyt9G6TuRPcntubCEHVefd5cmON7KGouseAaSmR5aGl0brcvaq9erzME",
	"xBVIlYEyFNCzHL0n65Dp2yXPrChHKPRxUu4DU4rt9rOo1R86kDnJ/iz7V7LqVyr1QyuxjewMk47L5VNV",
	"8z1FwDkZdRHaWxd6oE5ZKouCuXZpSi5egKxwqSGVwjFzCsoPqYwHy4wfUVsaayEv/7agHV32A4Q8Xd2e",
	"VijziYuVbPpKllr/fBP9gYFGJckXYAWddohvP38hrz5dkpVUpGDClLo18eHVEWGmP9QRMSlqfoqMGGpV",
	"RlyboHPM+1Y+GBVQgECjlUZ0C0o7U+dni7OFpXEJgpWcJvT52eLsOY3s+GJRjFnJ4+153Dhgvq1d9TRg",
	"2yb5MqMJfc81vmk2RYPB6GsY5G5L7MabOjq40Y8n9fVomPjfYnGvJp7l+cfVrGdN+Kf3jHFx1O0wZIMy",
	"vE9h02aGivGIQ9eB6cFgTOSqZYObHaqiYGrXLLM879ZNJV+bCNA2NNd1REupAxEcdHd+XgWNr2W2O9mA",
	"FOwg62Hmm+m4nsT3/HQ+NEGYAuyXiL9LTJxeOGaFFLYexr1ZdhgSd17CiIAfTVjCUamjSa7Fd/6/y6yO",
	"Xd7vTT87OurXuy6EoywMvEy0Fh72QPE7w71CN74/ML99rEPZbVcIF4QF6OQIMEcmntVuBMoBYcqgC/t9",
	"ljsHwnZ5EQrZi8k82KaYc8On2IvDKda+1QxRcV7vT60onDLvAE972sVTlqgMkPFcPxS/d4ANeORmRy4v",
	"DlYn23jsrUN21JmpPqMHxUHb+qD6E9LORZpXGSwbrgXfLWdeAn7XtEEX/NCS5lgTqGh2wTa7oYrmqHSo",
	"Z7EOPmbD0h80nrhbceBPgTXfuz5lvulAh80Y0HFCxwraYTYMdf8d45HADj2VHAV34J6xSog/1QQib8nT",
	"8gh4jrs9PREf6eq0IW/vzdA1OBPs+QvwhA4vnoby7b03ucbM4Sd3WK+AVAEIuneEX0fh9Hkwfd04Kgue",
	"KAL+wWoUAefz0eXG5JPpTgCf9Z4v9hQf7cj6tv/W8Uh51tkg1sNJ7dAN24YvL4Ezb+wr+Gy39A7QvZPT",
	"Rwzm6CU+ENbPoLY8BcI1cQ7vRkd2Kki6gbQfXe+7u/c1qG0TiVEPIFOWkwy2kMvSvkS5vTSilcppQjeI",
	"ZRLHudm3kRqTl4uXCxssb2msse8PAZGVkpvBp238vGOm7wl3z0X7KtYJte3uVMwOVkEhP3JNRWyqhCQc",
	"PWYEWkKRLYcf7rHWy/WYPxW+gJtq7TgZsumWveXr+p8AAAD///FnQDfGIAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
