// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/agent/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_EXEC        TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_EXEC",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_EXEC":        1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_SUCCESS     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 3
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_RUNNING",
		2: "EXECUTION_STATUS_SUCCESS",
		3: "EXECUTION_STATUS_FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_RUNNING":     1,
		"EXECUTION_STATUS_SUCCESS":     2,
		"EXECUTION_STATUS_FAILED":      3,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[1]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reset_        bool                   `protobuf:"varint,1,opt,name=reset,proto3" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type PollTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTasksRequest) Reset() {
	*x = PollTasksRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTasksRequest) ProtoMessage() {}

func (x *PollTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTasksRequest.ProtoReflect.Descriptor instead.
func (*PollTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PollTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PollTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTasksResponse) Reset() {
	*x = PollTasksResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTasksResponse) ProtoMessage() {}

func (x *PollTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTasksResponse.ProtoReflect.Descriptor instead.
func (*PollTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PollTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     TaskType               `protobuf:"varint,3,opt,name=type,proto3,enum=maestro.agent.v1.TaskType" json:"type,omitempty"`
	Blocking bool                   `protobuf:"varint,4,opt,name=blocking,proto3" json:"blocking,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*Task_Exec
	Config        isTask_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

func (x *Task) GetConfig() isTask_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Task) GetExec() *ExecConfig {
	if x != nil {
		if x, ok := x.Config.(*Task_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

type isTask_Config interface {
	isTask_Config()
}

type Task_Exec struct {
	Exec *ExecConfig `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

func (*Task_Exec) isTask_Config() {}

type ExecConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecConfig) Reset() {
	*x = ExecConfig{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecConfig) ProtoMessage() {}

func (x *ExecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecConfig.ProtoReflect.Descriptor instead.
func (*ExecConfig) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ExecConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecConfig) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ReportTaskExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=maestro.agent.v1.ExecutionStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskExecutionRequest) Reset() {
	*x = ReportTaskExecutionRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskExecutionRequest) ProtoMessage() {}

func (x *ReportTaskExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskExecutionRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskExecutionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportTaskExecutionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskExecutionRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ReportTaskExecutionRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportTaskExecutionRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportTaskExecutionRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportTaskExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskExecutionResponse) Reset() {
	*x = ReportTaskExecutionResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskExecutionResponse) ProtoMessage() {}

func (x *ReportTaskExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskExecutionResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ReportTaskExecutionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type PollDebugTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDebugTasksRequest) Reset() {
	*x = PollDebugTasksRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDebugTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDebugTasksRequest) ProtoMessage() {}

func (x *PollDebugTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDebugTasksRequest.ProtoReflect.Descriptor instead.
func (*PollDebugTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *PollDebugTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PollDebugTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DebugTasks    []*DebugTask           `protobuf:"bytes,1,rep,name=debug_tasks,json=debugTasks,proto3" json:"debug_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDebugTasksResponse) Reset() {
	*x = PollDebugTasksResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDebugTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDebugTasksResponse) ProtoMessage() {}

func (x *PollDebugTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDebugTasksResponse.ProtoReflect.Descriptor instead.
func (*PollDebugTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PollDebugTasksResponse) GetDebugTasks() []*DebugTask {
	if x != nil {
		return x.DebugTasks
	}
	return nil
}

type DebugTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DebugTask) Reset() {
	*x = DebugTask{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugTask) ProtoMessage() {}

func (x *DebugTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugTask.ProtoReflect.Descriptor instead.
func (*DebugTask) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DebugTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DebugTask) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DebugTask) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ReportDebugTaskExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DebugTaskId   string                 `protobuf:"bytes,2,opt,name=debug_task_id,json=debugTaskId,proto3" json:"debug_task_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=maestro.agent.v1.ExecutionStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDebugTaskExecutionRequest) Reset() {
	*x = ReportDebugTaskExecutionRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDebugTaskExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDebugTaskExecutionRequest) ProtoMessage() {}

func (x *ReportDebugTaskExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDebugTaskExecutionRequest.ProtoReflect.Descriptor instead.
func (*ReportDebugTaskExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReportDebugTaskExecutionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportDebugTaskExecutionRequest) GetDebugTaskId() string {
	if x != nil {
		return x.DebugTaskId
	}
	return ""
}

func (x *ReportDebugTaskExecutionRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ReportDebugTaskExecutionRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ReportDebugTaskExecutionRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportDebugTaskExecutionRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportDebugTaskExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDebugTaskExecutionResponse) Reset() {
	*x = ReportDebugTaskExecutionResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDebugTaskExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDebugTaskExecutionResponse) ProtoMessage() {}

func (x *ReportDebugTaskExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDebugTaskExecutionResponse.ProtoReflect.Descriptor instead.
func (*ReportDebugTaskExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReportDebugTaskExecutionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x10maestro.agent.v1\"g\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05reset\x18\x01 \x01(\bR\x05reset\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"-\n" +
	"\x10PollTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"A\n" +
	"\x11PollTasksResponse\x12,\n" +
	"\x05tasks\x18\x01 \x03(\v2\x16.maestro.agent.v1.TaskR\x05tasks\"\xb4\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.maestro.agent.v1.TaskTypeR\x04type\x12\x1a\n" +
	"\bblocking\x18\x04 \x01(\bR\bblocking\x122\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x1c.maestro.agent.v1.ExecConfigH\x00R\x04execB\b\n" +
	"\x06config\"p\n" +
	"\n" +
	"ExecConfig\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\"\xd6\x01\n" +
	"\x1aReportTaskExecutionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.maestro.agent.v1.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"A\n" +
	"\x1bReportTaskExecutionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"2\n" +
	"\x15PollDebugTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"V\n" +
	"\x16PollDebugTasksResponse\x12<\n" +
	"\vdebug_tasks\x18\x01 \x03(\v2\x1b.maestro.agent.v1.DebugTaskR\n" +
	"debugTasks\"^\n" +
	"\tDebugTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xe6\x01\n" +
	"\x1fReportDebugTaskExecutionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\rdebug_task_id\x18\x02 \x01(\tR\vdebugTaskId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.maestro.agent.v1.ExecutionStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"F\n" +
	" ReportDebugTaskExecutionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*9\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTASK_TYPE_EXEC\x10\x01*\x8c\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_SUCCESS\x10\x02\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x032\xea\x04\n" +
	"\fAgentService\x12Q\n" +
	"\bRegister\x12!.maestro.agent.v1.RegisterRequest\x1a\".maestro.agent.v1.RegisterResponse\x12T\n" +
	"\tHeartbeat\x12\".maestro.agent.v1.HeartbeatRequest\x1a#.maestro.agent.v1.HeartbeatResponse\x12T\n" +
	"\tPollTasks\x12\".maestro.agent.v1.PollTasksRequest\x1a#.maestro.agent.v1.PollTasksResponse\x12r\n" +
	"\x13ReportTaskExecution\x12,.maestro.agent.v1.ReportTaskExecutionRequest\x1a-.maestro.agent.v1.ReportTaskExecutionResponse\x12c\n" +
	"\x0ePollDebugTasks\x12'.maestro.agent.v1.PollDebugTasksRequest\x1a(.maestro.agent.v1.PollDebugTasksResponse\x12\x81\x01\n" +
	"\x18ReportDebugTaskExecution\x121.maestro.agent.v1.ReportDebugTaskExecutionRequest\x1a2.maestro.agent.v1.ReportDebugTaskExecutionResponseB+Z)github.com/filanov/maestro/proto/agent/v1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(TaskType)(0),                            // 0: maestro.agent.v1.TaskType
	(ExecutionStatus)(0),                     // 1: maestro.agent.v1.ExecutionStatus
	(*RegisterRequest)(nil),                  // 2: maestro.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),                 // 3: maestro.agent.v1.RegisterResponse
	(*HeartbeatRequest)(nil),                 // 4: maestro.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),                // 5: maestro.agent.v1.HeartbeatResponse
	(*PollTasksRequest)(nil),                 // 6: maestro.agent.v1.PollTasksRequest
	(*PollTasksResponse)(nil),                // 7: maestro.agent.v1.PollTasksResponse
	(*Task)(nil),                             // 8: maestro.agent.v1.Task
	(*ExecConfig)(nil),                       // 9: maestro.agent.v1.ExecConfig
	(*ReportTaskExecutionRequest)(nil),       // 10: maestro.agent.v1.ReportTaskExecutionRequest
	(*ReportTaskExecutionResponse)(nil),      // 11: maestro.agent.v1.ReportTaskExecutionResponse
	(*PollDebugTasksRequest)(nil),            // 12: maestro.agent.v1.PollDebugTasksRequest
	(*PollDebugTasksResponse)(nil),           // 13: maestro.agent.v1.PollDebugTasksResponse
	(*DebugTask)(nil),                        // 14: maestro.agent.v1.DebugTask
	(*ReportDebugTaskExecutionRequest)(nil),  // 15: maestro.agent.v1.ReportDebugTaskExecutionRequest
	(*ReportDebugTaskExecutionResponse)(nil), // 16: maestro.agent.v1.ReportDebugTaskExecutionResponse
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	8,  // 0: maestro.agent.v1.PollTasksResponse.tasks:type_name -> maestro.agent.v1.Task
	0,  // 1: maestro.agent.v1.Task.type:type_name -> maestro.agent.v1.TaskType
	9,  // 2: maestro.agent.v1.Task.exec:type_name -> maestro.agent.v1.ExecConfig
	1,  // 3: maestro.agent.v1.ReportTaskExecutionRequest.status:type_name -> maestro.agent.v1.ExecutionStatus
	14, // 4: maestro.agent.v1.PollDebugTasksResponse.debug_tasks:type_name -> maestro.agent.v1.DebugTask
	1,  // 5: maestro.agent.v1.ReportDebugTaskExecutionRequest.status:type_name -> maestro.agent.v1.ExecutionStatus
	2,  // 6: maestro.agent.v1.AgentService.Register:input_type -> maestro.agent.v1.RegisterRequest
	4,  // 7: maestro.agent.v1.AgentService.Heartbeat:input_type -> maestro.agent.v1.HeartbeatRequest
	6,  // 8: maestro.agent.v1.AgentService.PollTasks:input_type -> maestro.agent.v1.PollTasksRequest
	10, // 9: maestro.agent.v1.AgentService.ReportTaskExecution:input_type -> maestro.agent.v1.ReportTaskExecutionRequest
	12, // 10: maestro.agent.v1.AgentService.PollDebugTasks:input_type -> maestro.agent.v1.PollDebugTasksRequest
	15, // 11: maestro.agent.v1.AgentService.ReportDebugTaskExecution:input_type -> maestro.agent.v1.ReportDebugTaskExecutionRequest
	3,  // 12: maestro.agent.v1.AgentService.Register:output_type -> maestro.agent.v1.RegisterResponse
	5,  // 13: maestro.agent.v1.AgentService.Heartbeat:output_type -> maestro.agent.v1.HeartbeatResponse
	7,  // 14: maestro.agent.v1.AgentService.PollTasks:output_type -> maestro.agent.v1.PollTasksResponse
	11, // 15: maestro.agent.v1.AgentService.ReportTaskExecution:output_type -> maestro.agent.v1.ReportTaskExecutionResponse
	13, // 16: maestro.agent.v1.AgentService.PollDebugTasks:output_type -> maestro.agent.v1.PollDebugTasksResponse
	16, // 17: maestro.agent.v1.AgentService.ReportDebugTaskExecution:output_type -> maestro.agent.v1.ReportDebugTaskExecutionResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*Task_Exec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
