// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: proto/agent/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName                 = "/maestro.agent.v1.AgentService/Register"
	AgentService_Heartbeat_FullMethodName                = "/maestro.agent.v1.AgentService/Heartbeat"
	AgentService_PollTasks_FullMethodName                = "/maestro.agent.v1.AgentService/PollTasks"
	AgentService_ReportTaskExecution_FullMethodName      = "/maestro.agent.v1.AgentService/ReportTaskExecution"
	AgentService_PollDebugTasks_FullMethodName           = "/maestro.agent.v1.AgentService/PollDebugTasks"
	AgentService_ReportDebugTaskExecution_FullMethodName = "/maestro.agent.v1.AgentService/ReportDebugTaskExecution"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	PollTasks(ctx context.Context, in *PollTasksRequest, opts ...grpc.CallOption) (*PollTasksResponse, error)
	ReportTaskExecution(ctx context.Context, in *ReportTaskExecutionRequest, opts ...grpc.CallOption) (*ReportTaskExecutionResponse, error)
	PollDebugTasks(ctx context.Context, in *PollDebugTasksRequest, opts ...grpc.CallOption) (*PollDebugTasksResponse, error)
	ReportDebugTaskExecution(ctx context.Context, in *ReportDebugTaskExecutionRequest, opts ...grpc.CallOption) (*ReportDebugTaskExecutionResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PollTasks(ctx context.Context, in *PollTasksRequest, opts ...grpc.CallOption) (*PollTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollTasksResponse)
	err := c.cc.Invoke(ctx, AgentService_PollTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportTaskExecution(ctx context.Context, in *ReportTaskExecutionRequest, opts ...grpc.CallOption) (*ReportTaskExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskExecutionResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportTaskExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PollDebugTasks(ctx context.Context, in *PollDebugTasksRequest, opts ...grpc.CallOption) (*PollDebugTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollDebugTasksResponse)
	err := c.cc.Invoke(ctx, AgentService_PollDebugTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportDebugTaskExecution(ctx context.Context, in *ReportDebugTaskExecutionRequest, opts ...grpc.CallOption) (*ReportDebugTaskExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDebugTaskExecutionResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportDebugTaskExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	PollTasks(context.Context, *PollTasksRequest) (*PollTasksResponse, error)
	ReportTaskExecution(context.Context, *ReportTaskExecutionRequest) (*ReportTaskExecutionResponse, error)
	PollDebugTasks(context.Context, *PollDebugTasksRequest) (*PollDebugTasksResponse, error)
	ReportDebugTaskExecution(context.Context, *ReportDebugTaskExecutionRequest) (*ReportDebugTaskExecutionResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) PollTasks(context.Context, *PollTasksRequest) (*PollTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollTasks not implemented")
}
func (UnimplementedAgentServiceServer) ReportTaskExecution(context.Context, *ReportTaskExecutionRequest) (*ReportTaskExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskExecution not implemented")
}
func (UnimplementedAgentServiceServer) PollDebugTasks(context.Context, *PollDebugTasksRequest) (*PollDebugTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollDebugTasks not implemented")
}
func (UnimplementedAgentServiceServer) ReportDebugTaskExecution(context.Context, *ReportDebugTaskExecutionRequest) (*ReportDebugTaskExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDebugTaskExecution not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PollTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PollTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PollTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PollTasks(ctx, req.(*PollTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportTaskExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportTaskExecution(ctx, req.(*ReportTaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PollDebugTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollDebugTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PollDebugTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PollDebugTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PollDebugTasks(ctx, req.(*PollDebugTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportDebugTaskExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDebugTaskExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportDebugTaskExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportDebugTaskExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportDebugTaskExecution(ctx, req.(*ReportDebugTaskExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maestro.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "PollTasks",
			Handler:    _AgentService_PollTasks_Handler,
		},
		{
			MethodName: "ReportTaskExecution",
			Handler:    _AgentService_ReportTaskExecution_Handler,
		},
		{
			MethodName: "PollDebugTasks",
			Handler:    _AgentService_PollDebugTasks_Handler,
		},
		{
			MethodName: "ReportDebugTaskExecution",
			Handler:    _AgentService_ReportDebugTaskExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}
