// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/filanov/maestro/internal/db (interfaces: DB)

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/filanov/maestro/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDB)(nil).Close))
}

// CreateAgent mocks base method.
func (m *MockDB) CreateAgent(arg0 context.Context, arg1 *models.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockDBMockRecorder) CreateAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockDB)(nil).CreateAgent), arg0, arg1)
}

// CreateCluster mocks base method.
func (m *MockDB) CreateCluster(arg0 context.Context, arg1 *models.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockDBMockRecorder) CreateCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockDB)(nil).CreateCluster), arg0, arg1)
}

// CreateDebugTask mocks base method.
func (m *MockDB) CreateDebugTask(arg0 context.Context, arg1 *models.DebugTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDebugTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDebugTask indicates an expected call of CreateDebugTask.
func (mr *MockDBMockRecorder) CreateDebugTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDebugTask", reflect.TypeOf((*MockDB)(nil).CreateDebugTask), arg0, arg1)
}

// CreateExecution mocks base method.
func (m *MockDB) CreateExecution(arg0 context.Context, arg1 *models.TaskExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExecution", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExecution indicates an expected call of CreateExecution.
func (mr *MockDBMockRecorder) CreateExecution(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExecution", reflect.TypeOf((*MockDB)(nil).CreateExecution), arg0, arg1)
}

// CreateTask mocks base method.
func (m *MockDB) CreateTask(arg0 context.Context, arg1 *models.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockDBMockRecorder) CreateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockDB)(nil).CreateTask), arg0, arg1)
}

// CreateTemplate mocks base method.
func (m *MockDB) CreateTemplate(arg0 context.Context, arg1 *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockDBMockRecorder) CreateTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockDB)(nil).CreateTemplate), arg0, arg1)
}

// CreateTemplateTask mocks base method.
func (m *MockDB) CreateTemplateTask(arg0 context.Context, arg1 *models.TemplateTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplateTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTemplateTask indicates an expected call of CreateTemplateTask.
func (mr *MockDBMockRecorder) CreateTemplateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplateTask", reflect.TypeOf((*MockDB)(nil).CreateTemplateTask), arg0, arg1)
}

// DeleteAgent mocks base method.
func (m *MockDB) DeleteAgent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockDBMockRecorder) DeleteAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockDB)(nil).DeleteAgent), arg0, arg1)
}

// DeleteAllExecutionsForAgent mocks base method.
func (m *MockDB) DeleteAllExecutionsForAgent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllExecutionsForAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllExecutionsForAgent indicates an expected call of DeleteAllExecutionsForAgent.
func (mr *MockDBMockRecorder) DeleteAllExecutionsForAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllExecutionsForAgent", reflect.TypeOf((*MockDB)(nil).DeleteAllExecutionsForAgent), arg0, arg1)
}

// DeleteCluster mocks base method.
func (m *MockDB) DeleteCluster(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockDBMockRecorder) DeleteCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockDB)(nil).DeleteCluster), arg0, arg1)
}

// DeleteCompletedDebugTasksOlderThan mocks base method.
func (m *MockDB) DeleteCompletedDebugTasksOlderThan(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompletedDebugTasksOlderThan", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompletedDebugTasksOlderThan indicates an expected call of DeleteCompletedDebugTasksOlderThan.
func (mr *MockDBMockRecorder) DeleteCompletedDebugTasksOlderThan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompletedDebugTasksOlderThan", reflect.TypeOf((*MockDB)(nil).DeleteCompletedDebugTasksOlderThan), arg0, arg1)
}

// DeleteExecutionsForDeletedTasksOlderThan mocks base method.
func (m *MockDB) DeleteExecutionsForDeletedTasksOlderThan(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExecutionsForDeletedTasksOlderThan", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExecutionsForDeletedTasksOlderThan indicates an expected call of DeleteExecutionsForDeletedTasksOlderThan.
func (mr *MockDBMockRecorder) DeleteExecutionsForDeletedTasksOlderThan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExecutionsForDeletedTasksOlderThan", reflect.TypeOf((*MockDB)(nil).DeleteExecutionsForDeletedTasksOlderThan), arg0, arg1)
}

// DeleteOldExecutionsKeepLastN mocks base method.
func (m *MockDB) DeleteOldExecutionsKeepLastN(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldExecutionsKeepLastN", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldExecutionsKeepLastN indicates an expected call of DeleteOldExecutionsKeepLastN.
func (mr *MockDBMockRecorder) DeleteOldExecutionsKeepLastN(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldExecutionsKeepLastN", reflect.TypeOf((*MockDB)(nil).DeleteOldExecutionsKeepLastN), arg0, arg1)
}

// DeleteTask mocks base method.
func (m *MockDB) DeleteTask(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockDBMockRecorder) DeleteTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockDB)(nil).DeleteTask), arg0, arg1)
}

// DeleteTemplate mocks base method.
func (m *MockDB) DeleteTemplate(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockDBMockRecorder) DeleteTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockDB)(nil).DeleteTemplate), arg0, arg1)
}

// DeleteTemplateTask mocks base method.
func (m *MockDB) DeleteTemplateTask(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplateTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplateTask indicates an expected call of DeleteTemplateTask.
func (mr *MockDBMockRecorder) DeleteTemplateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplateTask", reflect.TypeOf((*MockDB)(nil).DeleteTemplateTask), arg0, arg1)
}

// ExportClusterToTemplate mocks base method.
func (m *MockDB) ExportClusterToTemplate(arg0 context.Context, arg1 string, arg2 *models.Template, arg3 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportClusterToTemplate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportClusterToTemplate indicates an expected call of ExportClusterToTemplate.
func (mr *MockDBMockRecorder) ExportClusterToTemplate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportClusterToTemplate", reflect.TypeOf((*MockDB)(nil).ExportClusterToTemplate), arg0, arg1, arg2, arg3)
}

// FailRunningTasksForAgent mocks base method.
func (m *MockDB) FailRunningTasksForAgent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailRunningTasksForAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailRunningTasksForAgent indicates an expected call of FailRunningTasksForAgent.
func (mr *MockDBMockRecorder) FailRunningTasksForAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailRunningTasksForAgent", reflect.TypeOf((*MockDB)(nil).FailRunningTasksForAgent), arg0, arg1)
}

// FindAgentsWithHeartbeatBefore mocks base method.
func (m *MockDB) FindAgentsWithHeartbeatBefore(arg0 context.Context, arg1 time.Time) ([]*models.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAgentsWithHeartbeatBefore", arg0, arg1)
	ret0, _ := ret[0].([]*models.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAgentsWithHeartbeatBefore indicates an expected call of FindAgentsWithHeartbeatBefore.
func (mr *MockDBMockRecorder) FindAgentsWithHeartbeatBefore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAgentsWithHeartbeatBefore", reflect.TypeOf((*MockDB)(nil).FindAgentsWithHeartbeatBefore), arg0, arg1)
}

// GetAgent mocks base method.
func (m *MockDB) GetAgent(arg0 context.Context, arg1 string) (*models.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*models.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockDBMockRecorder) GetAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockDB)(nil).GetAgent), arg0, arg1)
}

// GetCluster mocks base method.
func (m *MockDB) GetCluster(arg0 context.Context, arg1 string) (*models.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", arg0, arg1)
	ret0, _ := ret[0].(*models.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockDBMockRecorder) GetCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockDB)(nil).GetCluster), arg0, arg1)
}

// GetDebugTask mocks base method.
func (m *MockDB) GetDebugTask(arg0 context.Context, arg1 string) (*models.DebugTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebugTask", arg0, arg1)
	ret0, _ := ret[0].(*models.DebugTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDebugTask indicates an expected call of GetDebugTask.
func (mr *MockDBMockRecorder) GetDebugTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebugTask", reflect.TypeOf((*MockDB)(nil).GetDebugTask), arg0, arg1)
}

// GetExecution mocks base method.
func (m *MockDB) GetExecution(arg0 context.Context, arg1 string) (*models.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecution", arg0, arg1)
	ret0, _ := ret[0].(*models.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecution indicates an expected call of GetExecution.
func (mr *MockDBMockRecorder) GetExecution(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecution", reflect.TypeOf((*MockDB)(nil).GetExecution), arg0, arg1)
}

// GetExecutionsForAgent mocks base method.
func (m *MockDB) GetExecutionsForAgent(arg0 context.Context, arg1 string) ([]*models.TaskExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionsForAgent", arg0, arg1)
	ret0, _ := ret[0].([]*models.TaskExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionsForAgent indicates an expected call of GetExecutionsForAgent.
func (mr *MockDBMockRecorder) GetExecutionsForAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionsForAgent", reflect.TypeOf((*MockDB)(nil).GetExecutionsForAgent), arg0, arg1)
}

// GetPendingDebugTasksForAgent mocks base method.
func (m *MockDB) GetPendingDebugTasksForAgent(arg0 context.Context, arg1 string) ([]*models.DebugTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingDebugTasksForAgent", arg0, arg1)
	ret0, _ := ret[0].([]*models.DebugTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingDebugTasksForAgent indicates an expected call of GetPendingDebugTasksForAgent.
func (mr *MockDBMockRecorder) GetPendingDebugTasksForAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingDebugTasksForAgent", reflect.TypeOf((*MockDB)(nil).GetPendingDebugTasksForAgent), arg0, arg1)
}

// GetTask mocks base method.
func (m *MockDB) GetTask(arg0 context.Context, arg1 string) (*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockDBMockRecorder) GetTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockDB)(nil).GetTask), arg0, arg1)
}

// GetTasksForCluster mocks base method.
func (m *MockDB) GetTasksForCluster(arg0 context.Context, arg1 string) ([]*models.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksForCluster", arg0, arg1)
	ret0, _ := ret[0].([]*models.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksForCluster indicates an expected call of GetTasksForCluster.
func (mr *MockDBMockRecorder) GetTasksForCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksForCluster", reflect.TypeOf((*MockDB)(nil).GetTasksForCluster), arg0, arg1)
}

// GetTemplate mocks base method.
func (m *MockDB) GetTemplate(arg0 context.Context, arg1 string) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", arg0, arg1)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockDBMockRecorder) GetTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockDB)(nil).GetTemplate), arg0, arg1)
}

// GetTemplateTask mocks base method.
func (m *MockDB) GetTemplateTask(arg0 context.Context, arg1 string) (*models.TemplateTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateTask", arg0, arg1)
	ret0, _ := ret[0].(*models.TemplateTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateTask indicates an expected call of GetTemplateTask.
func (mr *MockDBMockRecorder) GetTemplateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateTask", reflect.TypeOf((*MockDB)(nil).GetTemplateTask), arg0, arg1)
}

// GetTemplateTasksForTemplate mocks base method.
func (m *MockDB) GetTemplateTasksForTemplate(arg0 context.Context, arg1 string) ([]*models.TemplateTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateTasksForTemplate", arg0, arg1)
	ret0, _ := ret[0].([]*models.TemplateTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateTasksForTemplate indicates an expected call of GetTemplateTasksForTemplate.
func (mr *MockDBMockRecorder) GetTemplateTasksForTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateTasksForTemplate", reflect.TypeOf((*MockDB)(nil).GetTemplateTasksForTemplate), arg0, arg1)
}

// ImportTemplateToCluster mocks base method.
func (m *MockDB) ImportTemplateToCluster(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportTemplateToCluster", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportTemplateToCluster indicates an expected call of ImportTemplateToCluster.
func (mr *MockDBMockRecorder) ImportTemplateToCluster(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportTemplateToCluster", reflect.TypeOf((*MockDB)(nil).ImportTemplateToCluster), arg0, arg1, arg2)
}

// ListAgents mocks base method.
func (m *MockDB) ListAgents(arg0 context.Context, arg1 string, arg2 *models.AgentStatus, arg3, arg4 int) ([]*models.Agent, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*models.Agent)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockDBMockRecorder) ListAgents(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockDB)(nil).ListAgents), arg0, arg1, arg2, arg3, arg4)
}

// ListClusters mocks base method.
func (m *MockDB) ListClusters(arg0 context.Context, arg1, arg2 int) ([]*models.Cluster, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Cluster)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockDBMockRecorder) ListClusters(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockDB)(nil).ListClusters), arg0, arg1, arg2)
}

// ListDebugTasks mocks base method.
func (m *MockDB) ListDebugTasks(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*models.DebugTask, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDebugTasks", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.DebugTask)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDebugTasks indicates an expected call of ListDebugTasks.
func (mr *MockDBMockRecorder) ListDebugTasks(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDebugTasks", reflect.TypeOf((*MockDB)(nil).ListDebugTasks), arg0, arg1, arg2, arg3)
}

// ListExecutions mocks base method.
func (m *MockDB) ListExecutions(arg0 context.Context, arg1 ExecutionFilters, arg2, arg3 int) ([]*models.TaskExecution, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExecutions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.TaskExecution)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExecutions indicates an expected call of ListExecutions.
func (mr *MockDBMockRecorder) ListExecutions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExecutions", reflect.TypeOf((*MockDB)(nil).ListExecutions), arg0, arg1, arg2, arg3)
}

// ListTasks mocks base method.
func (m *MockDB) ListTasks(arg0 context.Context, arg1 string, arg2 bool, arg3, arg4 int) ([]*models.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*models.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockDBMockRecorder) ListTasks(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockDB)(nil).ListTasks), arg0, arg1, arg2, arg3, arg4)
}

// ListTemplateTasks mocks base method.
func (m *MockDB) ListTemplateTasks(arg0 context.Context, arg1 string, arg2, arg3 int) ([]*models.TemplateTask, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplateTasks", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*models.TemplateTask)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTemplateTasks indicates an expected call of ListTemplateTasks.
func (mr *MockDBMockRecorder) ListTemplateTasks(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplateTasks", reflect.TypeOf((*MockDB)(nil).ListTemplateTasks), arg0, arg1, arg2, arg3)
}

// ListTemplates mocks base method.
func (m *MockDB) ListTemplates(arg0 context.Context, arg1, arg2 int) ([]*models.Template, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockDBMockRecorder) ListTemplates(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockDB)(nil).ListTemplates), arg0, arg1, arg2)
}

// ReorderTasks mocks base method.
func (m *MockDB) ReorderTasks(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderTasks", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderTasks indicates an expected call of ReorderTasks.
func (mr *MockDBMockRecorder) ReorderTasks(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderTasks", reflect.TypeOf((*MockDB)(nil).ReorderTasks), arg0, arg1, arg2)
}

// ReorderTemplateTasks mocks base method.
func (m *MockDB) ReorderTemplateTasks(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderTemplateTasks", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderTemplateTasks indicates an expected call of ReorderTemplateTasks.
func (mr *MockDBMockRecorder) ReorderTemplateTasks(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderTemplateTasks", reflect.TypeOf((*MockDB)(nil).ReorderTemplateTasks), arg0, arg1, arg2)
}

// ResetExecutionsForTask mocks base method.
func (m *MockDB) ResetExecutionsForTask(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetExecutionsForTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetExecutionsForTask indicates an expected call of ResetExecutionsForTask.
func (mr *MockDBMockRecorder) ResetExecutionsForTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetExecutionsForTask", reflect.TypeOf((*MockDB)(nil).ResetExecutionsForTask), arg0, arg1)
}

// TimeoutPendingDebugTasks mocks base method.
func (m *MockDB) TimeoutPendingDebugTasks(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeoutPendingDebugTasks", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TimeoutPendingDebugTasks indicates an expected call of TimeoutPendingDebugTasks.
func (mr *MockDBMockRecorder) TimeoutPendingDebugTasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeoutPendingDebugTasks", reflect.TypeOf((*MockDB)(nil).TimeoutPendingDebugTasks), arg0, arg1)
}

// UpdateAgent mocks base method.
func (m *MockDB) UpdateAgent(arg0 context.Context, arg1 string, arg2 *AgentUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgent indicates an expected call of UpdateAgent.
func (mr *MockDBMockRecorder) UpdateAgent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgent", reflect.TypeOf((*MockDB)(nil).UpdateAgent), arg0, arg1, arg2)
}

// UpdateAgentStatus mocks base method.
func (m *MockDB) UpdateAgentStatus(arg0 context.Context, arg1 string, arg2 models.AgentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentStatus indicates an expected call of UpdateAgentStatus.
func (mr *MockDBMockRecorder) UpdateAgentStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentStatus", reflect.TypeOf((*MockDB)(nil).UpdateAgentStatus), arg0, arg1, arg2)
}

// UpdateDebugTaskExecution mocks base method.
func (m *MockDB) UpdateDebugTaskExecution(arg0 context.Context, arg1 string, arg2 models.ExecutionStatus, arg3 string, arg4 *int, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDebugTaskExecution", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDebugTaskExecution indicates an expected call of UpdateDebugTaskExecution.
func (mr *MockDBMockRecorder) UpdateDebugTaskExecution(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDebugTaskExecution", reflect.TypeOf((*MockDB)(nil).UpdateDebugTaskExecution), arg0, arg1, arg2, arg3, arg4, arg5)
}

// UpdateTask mocks base method.
func (m *MockDB) UpdateTask(arg0 context.Context, arg1 string, arg2 *TaskUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockDBMockRecorder) UpdateTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockDB)(nil).UpdateTask), arg0, arg1, arg2)
}

// UpdateTemplate mocks base method.
func (m *MockDB) UpdateTemplate(arg0 context.Context, arg1 string, arg2 *TemplateUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockDBMockRecorder) UpdateTemplate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockDB)(nil).UpdateTemplate), arg0, arg1, arg2)
}

// UpdateTemplateTask mocks base method.
func (m *MockDB) UpdateTemplateTask(arg0 context.Context, arg1 string, arg2 *TemplateTaskUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTemplateTask indicates an expected call of UpdateTemplateTask.
func (mr *MockDBMockRecorder) UpdateTemplateTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplateTask", reflect.TypeOf((*MockDB)(nil).UpdateTemplateTask), arg0, arg1, arg2)
}

// UpsertExecution mocks base method.
func (m *MockDB) UpsertExecution(arg0 context.Context, arg1 *models.TaskExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExecution", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExecution indicates an expected call of UpsertExecution.
func (mr *MockDBMockRecorder) UpsertExecution(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExecution", reflect.TypeOf((*MockDB)(nil).UpsertExecution), arg0, arg1)
}
